@startuml
'https://plantuml.com/class-diagram

class fereastra_autorizare_locatie_GPS {

buton_permite
buton_nu_permite
text_Permiteti_ca_aplicatia_sa_utilizeze_locatia_dumneavoastra
gestioneaza_actiunea_cu_permite_accesul_la_serviciul_GPS()
gestioneaza_actiunea_cu_nu_permite_acces_la_serviciul_GPS()
afiseaza_text_informativ()
}

class serviciile_GPS{
cache
locatia_curenta_obtinuta_prin_GPS
inregistreaza_date_in_cache()
incepe_obtinerea_locatiei_GPS()
opreste_obtinerea-locatiei_GPS()
}

fereastra_autorizare_locatie_GPS - serviciile_GPS :> cerere

class selectie_limba_preferata{

drop_down_list
text_limba_romana
text_limba_engleza
Buton_pentru_Continuare
afiseaza_text_romana()
afiseaza_text_engleza()
afiseaza_pagina_principala()
}


class fereastra_lucru_engleza{
Text_informativ_cu_"subconstruction system"
desen_simbolic
buton_"Next"
afiseaza_text_informativ()
inchide_fereastra_lucru_engleza()
}
selectie_limba_preferata ---* fereastra_lucru_engleza
selectie_limba_preferata ---* Pagina_principala

class APIgoogleMap{
harta_obtinuta_prin_googleMap
cache
incepe_obtinerea_hartii()
inregistreaza_date_in_cache()
}
note right: Control
selectie_limba_preferata - APIgoogleMap :> cerere


class Pagina_principala{
buton_notificari
buton_informti
drop_down_list_statie
harta_timisoara
buton_apropiere_distantiere
buton_tur_retur
autobuz_program
trolebuz_program
tramvai_program
afiseaza_fereastra_notificari()
afiseaza_fereastra_informatii()
afiseaza_stiile()
afiseaza_traseul_si_statie()
apropie_sau_distantiaza_harta()
afiseaza_sensul_traseului()
afiseaza_program_intreg_autobuz()
afiseaza_program_intreg_trolebuz()
afiseaza_program_intreg_tramvai()


}
class buton_notificari{
icon_afisat_pe_buton
Nr_de_notificari_necitite
actiunea_click_apasare
afiseaza_numar_notificari()
afiseaza_fereastra_notificari()
afiseaza_numarul_necitite()
}

note left:Entity
note right of buton_notificari::icon_afisat_pe_buton
 Bondary
 end note

class fereastra_notificari{
Label
lista_notificari
afiseaza_notificarile_text()
}
buton_notificari"1"--*"*" fereastra_notificari

class APItrafic{
notificari_obtinute_prin_API
cache
incepe_obtinerea_notificarilor()
inregistreaza_date_in_cache()
}
buton_notificari - APItrafic:> cerere

class buton_informti{
icon_afisat_pe_buton
afiseaza_fereastra_informatii()
}
note left: Entyti
class fereastra_informatii{
Label
afiseaza_informatii()
}
buton_informti--* fereastra_informatii
note left: Entyti

class drop_down_list_statie{
lista_statii_disponibile_apropiate
actiunea_click_apasare
sageata_ce_indica_dropdown_inchis_deschis
afiseaza_fereastra_selectie_linie_autobuz()
sageata_in_jos_inchis()
sageata_in_sus_deschis()
}
class APItrasnport{
program_obtinut_prin_API
cache
incepe_obtinerea_programului()
inregistreaza_date_in_cache()
}
drop_down_list_statie - APItrasnport:> cerere
note right:control

class fereastra_selectie_linie_autobuz{
lista_linii_autobuz_pt_statia_selectata
program_ora_sosire_fiecare_linie
afiseaza_lista_linii_trasnport()
afiseaza_ora_sosire()
afiseaza_fereastra_program_linie_tot_traseul()
evidentiaza_traseul_pe_harta()
}
drop_down_list_statie--* fereastra_selectie_linie_autobuz

class program_linie_tot_traseul{
Lista_statii_pt_linia_selectata_tot_traseul
program_ora_sosire_fiecare_statie

afiseaza_lista_statii_tot_traseul()
afiseaza_program_sosire_tot_traseul()
}
fereastra_selectie_linie_autobuz--*program_linie_tot_traseul
fereastra_selectie_linie_autobuz--*harta_timisoara
class harta_timisoara{
traseu
autobuz
statie
afiseaza_traseul()
afiseaza_autobuz_pe_traseu()
afiseaza_stiile()

}

class program_intreg_linie_trasnport3B{
program_toata_saptamana_trolebuz
program_toata_saptamana_tramvai
program_toata_saptamana_autobuz
afiseaza_fereastra_trolebuz_program()
afiseaza_fereastra_tramvai_program()
afiseaza_fereastra_autobuz_program()
}
class trolebuz_program3B{
icon_afisat_pe_buton
lista_linii_trolebuz
afiseaza_lista_toate_liniile_de_trolebuz()
}
class tramvai_program3B{
icon_afisat_pe_buton
lista_linii_tramvai
afiseaza_lista_toate_liniile_de_tramvai()
}
class autobuz_program3B{
icon_afisat_pe_buton
lista_linii_autobuz
afiseaza_lista_toate_liniile_de_autobuz()
}

trolebuz_program3B--*program_intreg_linie_trasnport3B
tramvai_program3B--*program_intreg_linie_trasnport3B
autobuz_program3B--*program_intreg_linie_trasnport3B

class buton_tur_retur{
icon_sageata_tur
icon_sageata_retur
arata_sensul_tur()
arata_sensul_retur()
}

class buton_apropiere_distantiere{
icon_cu_plus
icon_cu_minus
apropie_de_harta()
distantiaza_de_harta()
}


class statie{
nr_GPS
numar_autobuze
adresa
afiseaza_nr_autobuze()
afiseaza_adresa()
}
class traseu {
nume_traseu
lista_toate_statiile_de_pe_traseu
coordonate_GPS_autobuz
evidentiaza_traseu_desenat_pe_harta()
evidentiaza_staiile_pe_traseu()
evidentiaza_live_locatia_autobuzlui()
}
class autobuz{
icon_autobuz
cordonate-autobuz
evidentiaza_live_locatia_autobuzului()
}

harta_timisoara--*traseu
harta_timisoara--*statie
harta_timisoara--*autobuz
harta_timisoara--*buton_tur_retur
traseu-* buton_tur_retur
harta_timisoara--*buton_apropiere_distantiere



@enduml