@startuml
@startuml
'idea.partialRender
@startuml
actor utilizator
:utilizator:--->(initiaza o cerere de permisiune GPS):selecteaza permite acces
:utilizator:--->(nu inregistreaza coordonatele GPS):selecteaza nu permite acces
actor GPSservice
GPSservice<--(initiaza o cerere de permisiune GPS)
GPSservice--> (inregistreaza coordonate GPS)
(inregistreaza coordonate GPS)--|> utilizator
utilizator -->(traduce automat in limba selectata): selectarea limbii preferate
utilizator --> (afiseaza pagina principala): selecteaza butonul continue
(nu inregistreaza coordonatele GPS)---|>(afiseaza pagina principala):nu afiseaza coordonatele gps
(inregistreaza coordonate GPS)---|>(afiseaza pagina principala):afiseaza coordonate GPS
utilizator --> (Afiseaza alerte/notificarile) : apasa butonul cu clopotel
utilizator --> ( afiseaza o casuta cu Buletin informativ, unde descrie informatia despre bilete) : apasa butonul cu informatii
utilizator-->(afiseaza statiile detectate dupa locatia utilizatorului): alege o statie din cele detectate apropiate
:utilizator:-up-->( afiseaza toate statiile ):selecteaza nu permite acces coordonate GPS
:utilizator:-up-->(afiseaza liniile  mijloacele de trasnport ce opresc in statia respectiva):selecteaza statie din dropdown list
:utilizator:-up-->(afiseaza program linie de trasnport ales):selecteaza linie mijloc de trasnport
utilizator --->(afiseaza programul pentru mijlocul de trasnport):selecteaza un tip de trasnport autobuz/firobuz/tramvai

:utilizator:-up-->(afiseaza traseul pe harta cu linie ingrosata):selectat nr mijlocului de transport
:utilizator:-right-->(mareste/apropie harta):apasa plus/minus
:utilizator:-right--> (schimba directia sagetilor):selecteaza tur/retur







@enduml
